# Base image
FROM python

# Set working directory
WORKDIR /app

# Copy files
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Default command to run Python script
CMD ["python", "aggregator.py"]
